services:
  authentik-postgresql:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - authentik_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: authentik
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    restart: unless-stopped

  authentik-redis:
    image: redis:7-alpine
    ports:
      - 6380:6379
    volumes:
      - authentik_redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "authentik"]

  authentik-server:
    image: ghcr.io/goauthentik/server:2024.10.1
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_REDIS__PASSWORD: authentik
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik
      AUTHENTIK_SECRET_KEY: "authentik-secret-key-change-this-in-production"
    volumes:
      - authentik_media:/media
      - authentik_custom_templates:/templates
    ports:
      - "9443:9443"
      - "9080:9000"
    depends_on:
      - authentik-postgresql
      - authentik-redis

  authentik-worker:
    image: ghcr.io/goauthentik/server:2024.10.1
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_REDIS__PASSWORD: authentik
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik
      AUTHENTIK_SECRET_KEY: "authentik-secret-key-change-this-in-production"
    volumes:
      - authentik_media:/media
      - authentik_custom_templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - authentik-postgresql
      - authentik-redis

volumes:
  authentik_postgres_data:
  authentik_redis_data:
  authentik_media:
  authentik_custom_templates: